### ISSUE TITLE
The request lacks valid authentication credentials

### ISSUE THREAD

**Issue by fairlygood** [skpy/micropub#9]
I'm receiving the following error when trying to post to my Hugo site via Micropub clients (I've tried various with the same error):

{"error":"insufficient_scope","error_description":"The request lacks valid authentication credentials"}

I believe that I have followed the installation instructions correctly and I am able to successfully authorise with indiauth.com

Any pointers for how I could start troubleshooting this?

**Comment by skpy** [comment]
I know I ran into the same error at least once while working on this; but I can't remember what the root cause was nor how I overcame it.

That error only happens [on line 100 of common.php](https://github.com/skpy/micropub/blob/master/inc/common.php#L100).  

To debug, you can try to insert a new line after line 96 of common.php with something like this:
```
file_put_contents('/tmp/debug.txt', print_r($response, true));
```

You may need to adjust where you write the file, based on permissions and such.  That should at least show you what the endpoint is sending back.

The `indieAuth()` function is invoked from `index.php`:
```
indieAuth($config['token_endpoint'], $headers['authorization'], $config['base_url']);
```

It's using whatever you have defined in `$config['base_url']` as the `$me` value.  The default for that is `'https://' . $_SERVER['HTTP_HOST'] .'/'`, so you may be having some mismatches between what your server thinks of itself and what your IndieAuth endpoint thinks of your server.  I seem to recall there being some weird edge cases with that.

If you're not setting the `base_url` value explicitly, that would be another thing to try.

**Comment by fairlygood** [comment]
Thanks for the suggestions. I'll try it out.
